### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by fherrerao** [Bondok6/Leaderboard#4]
# Hi @Bondok6 💯 

- Good job Kyrillos.
- Your code is clean.
- You have used async and await with the fetch method to send and receive data.
- Your project looks great 
![](https://media.giphy.com/media/1zN2433DxGL4I/giphy.gif)

**Comment by Bondok6** [comment]
# Hi @fherrerao 🙋‍♂️

Thanks for your review. 🙏
